pipeline:
  build:
    image: golang:1.8
    commands:
    - apt-get update && apt-get install -y --no-install-recommends upx-ucl
    - make build
  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: cblomart/rpi-registry